### ISSUE TITLE
sqlite insertation error

### ISSUE THREAD

**Issue by chemstar** [coreGreenberet/homematicip-devicelogger#1]
Hi,
on my HMIP-SWDO the rssiPeerValue  is set to None.

DeviceLogger cause an following error when
shuttercontact.rssiPeerValue = None 

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3830, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: shuttercontact.rssiPeerValue

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "homematicip_logger.py", line 50, in <module>
    main()
  File "homematicip_logger.py", line 41, in main
    write_shutter(g.label,d)
  File "homematicip_logger.py", line 16, in write_shutter
    models.ShutterContact.create(roomname=room, hmip_id=device.id, label=device.label, lastStatusUpdate=device.lastSt                                                                                                                        atusUpdate, open=device.windowState=='OPEN', rssiPeerValue=device.rssiPeerValue, rssiDeviceValue=device.rssiDeviceVal                                                                                                                        ue)
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 4977, in create
    inst.save(force_insert=True)
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 5170, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3584, in execute
    cursor = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 2939, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3837, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3656, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3830, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: shuttercontact.rssiPeerValue

**Comment by coreGreenberet** [comment]
this is fixed now. rssi values can contain null values now.
however if you have an existing database you would have to change that to allow null values now
