### ISSUE TITLE
sqlite insertation error #2

### ISSUE THREAD

**Issue by chemstar** [coreGreenberet/homematicip-devicelogger#2]
Hi,
on my HMIP-eTRV the valvePosition is set to None (could be because of lowbat=true)

DeviceLogger cause an following error when
valvePosition=None

`HMIP-eTRV Heizkörperthermostat ROOM lowbat(True) unreach(True) rssiDeviceValue(-59) rssiPeerValue(-62) configPending(False) dutyCycle(False): operationLockActive(False) valvePosition(None) valveState(ERROR_POSITION) temperatureOffset(0.0) setPointTemperature(15.0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2625, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: heatingthermostat.valvePosition

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "homematicip_logger.py", line 52, in <module>
    main()
  File "homematicip_logger.py", line 45, in main
    write_heatingthermostat(g.label,d)
  File "homematicip_logger.py", line 23, in write_heatingthermostat
    models.HeatingThermostat.create(roomname=room, hmip_id=device.id, label=device.label, lastStatusUpdate=device.lastStatusUpdate, valvePosition=device.valvePosition, rssiPeerValue=device.rssiPeerValue, rssiDeviceValue=device.rssiDeviceValue)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 5393, in create
    inst.save(force_insert=True)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 5516, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 1560, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 1631, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2274, in _execute
    return super(Insert, self)._execute(database)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2049, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2638, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2632, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2424, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 177, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2625, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: heatingthermostat.valvePosition`

**Comment by coreGreenberet** [comment]
I've made all fields nullable now. However an existing db must be converted via SQL or you are recreating it
